---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  cleanup:filesystem:
    desc: Cleanup the filesystem for this project
    cmds:
      - rm -rf .cache
      - rm -rf node_modules
      - rm -rf target
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +

  cleanup:
    desc: Cleanup the development environment for this project
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - task: cleanup:filesystem

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - task: cleanup:filesystem
      - for: ['yaml', 'filenames', 'folders', 'dockerfile'] # , 'workflows', 'markdown-links'
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  copilot:lint-and-fix:
    desc: 'Use GitHub Copilot to lint and fix issues in the project'
    cmds:
      - task: cleanup
      - copilot --allow-all --prompt "/lint-and-fix"

  copilot:pull-request:
    desc: 'Use GitHub Copilot to create or update a pull request with a summary of all changes based on commit messages'
    cmds:
      - copilot --allow-all --prompt "/create-or-update-pull-request"

  # ===============================================================================================

  radar:build:
    desc: 'Build the tech radar'
    cmds:
      - npm install
      - npm run build:radar

  radar:run:
    desc: 'Build and serve the tech radar on http://localhost:8080'
    cmds:
      - task: cleanup
      - task: radar:build
      - echo "Starting web server on http://localhost:8080"
      - npm run serve:radar

  docker:build:
    desc: 'Build the tech radar Docker image'
    cmds:
      - docker compose up lint-dockerfile --exit-code-from lint-dockerfile
      - docker compose build

  docker:run:
    desc: 'Run the tech radar Docker image'
    cmds:
      - task: docker:build
      - docker compose up radar --exit-code-from radar
