---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose down --remove-orphans
      - rm -rf .cache
      - rm -rf node_modules
      - rm -rf target
      - find . -type f -exec chmod +r {} +
      - find . -type d -exec chmod +r {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for: ['yaml', 'filenames', 'folders', 'dockerfile'] # , 'workflows', 'markdown-links'
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  radar:build:
    desc: 'Build the tech radar'
    cmds:
      - npm install
      - npm run build:radar

  radar:run:
    desc: 'Build and serve the tech radar on http://localhost:8080'
    cmds:
      - task: cleanup
      - task: radar:build
      - echo "Starting web server on http://localhost:8080"
      - npm run serve:radar

  docker:build:
    desc: 'Build the tech radar Docker image'
    cmds:
      - docker compose up lint-dockerfile --exit-code-from lint-dockerfile
      - docker compose build

  docker:run:
    desc: 'Run the tech radar Docker image'
    cmds:
      - task: docker:build
      - docker compose up radar --exit-code-from radar
